language: java

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

before_script:
    - ./gradlew --version

script:
    - TERM=dumb ./gradlew build jacocoTestReport --scan -Dorg.gradle.parallel=true

jdk:
    - oraclejdk8
    - openjdk9
    - openjdk10

after_success:
    - ./gradlew coveralls
